on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v2
      - name: Validate schema
        run: |
          echo ::set-env name=OUTPUT::$(bin/validate)
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{ env.OUTPUT }}
      - name: Concat schema
        run: bin/concat
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
